resolver: lts-21.0

packages:
- .

extra-deps:
- language-lua-0.11.0.1
- git: git@github.com:jkoppel/language-javascript.git
  commit: 3b2026cf9c443bc798683c12206de439354283ce
- language-dot-0.1.1
- git: git@github.com:jkoppel/language-c.git
  commit: 49c340419e9ea6395c1915f9de7aedf903483c95
- git: git@github.com:jkoppel/language-java.git
  commit: a41ba850a1e2b3e233cc8e5132433921b6a6dca0
- language-python-0.5.8
- concurrent-supply-0.1.8
- wl-pprint-1.2.1@sha256:aea676cff4a062d7d912149d270e33f5bb0c01b68a9db46ff13b438141ff4b7c,734
- alex-tools-0.6.1
- git: git@github.com:jkoppel/cubix.git
  commit: 3369376c6b18e690f847a1558ab53e36daf003b8 # release-0.7
  subdirs:
  - .
  - compdata
  - compstrat
  - comptrans