resolver: lts-23.19

packages:
- .

extra-deps:
- language-lua-0.11.0.2
- git: https://github.com/jkoppel/language-javascript.git
  commit: 516f52b13870fa7d99b0503a0730438f07891340
- language-dot-0.1.2
- git: https://github.com/jkoppel/language-c.git
  commit: 9a496ea8da36742ab3c4ca7769f072f8f6091deb
- git: https://github.com/jkoppel/language-java.git
  commit: 31de71c063d8586d6d69f49fbc55030f7e865593
- git: https://github.com/jkoppel/language-python.git
  commit: 4ef1ba415badfb58e043bef543d9d9857ab0f2cc
  subdirs:
   - language-python
- concurrent-supply-0.1.8
- wl-pprint-1.2.1@sha256:aea676cff4a062d7d912149d270e33f5bb0c01b68a9db46ff13b438141ff4b7c,734
- alex-tools-0.6.1
- git: https://github.com/jkoppel/solidity-hs
  commit: ed56714c994693e7458ad5f5b02d6bb1c53fe435
- git: https://github.com/jkoppel/cubix.git
  commit: 39c12de365aee9a12095b48922cda6e5f81bfbac
  subdirs:
  - .
  - compdata
  - compstrat
  - comptrans
